// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "scNPM_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MCMC_with_difficulty_based_matching
List MCMC_with_difficulty_based_matching(const int num_iter, const int num_save, mat theta_t, mat ind_zero, mat mu_treat, mat mu_ctrl, cube invcov_treat, cube cov_treat, cube invcov_ctrl, cube cov_ctrl, cube edge_treat, cube edge_ctrl, vec group_treat, vec group_ctrl, vec lambda0_t, vec lambda1_t, vec pi_treat, vec pi_ctrl, vec gam, mat cell_t, const int G, const int N_int, const int K, double ssp_v0, double ssp_v1, double ssp_l, double ssp_xi, double epsilon_theta, int num_step_theta, double eta_mu, double tau_sq_mu, double lam0_0, double lam1_0, double sigma2_lam0, double sigma2_lam1, double edge_prob_threshold, double edge_prob_adj, double epsilon_lam, int num_step_lam);
RcppExport SEXP _scNPM_MCMC_with_difficulty_based_matching(SEXP num_iterSEXP, SEXP num_saveSEXP, SEXP theta_tSEXP, SEXP ind_zeroSEXP, SEXP mu_treatSEXP, SEXP mu_ctrlSEXP, SEXP invcov_treatSEXP, SEXP cov_treatSEXP, SEXP invcov_ctrlSEXP, SEXP cov_ctrlSEXP, SEXP edge_treatSEXP, SEXP edge_ctrlSEXP, SEXP group_treatSEXP, SEXP group_ctrlSEXP, SEXP lambda0_tSEXP, SEXP lambda1_tSEXP, SEXP pi_treatSEXP, SEXP pi_ctrlSEXP, SEXP gamSEXP, SEXP cell_tSEXP, SEXP GSEXP, SEXP N_intSEXP, SEXP KSEXP, SEXP ssp_v0SEXP, SEXP ssp_v1SEXP, SEXP ssp_lSEXP, SEXP ssp_xiSEXP, SEXP epsilon_thetaSEXP, SEXP num_step_thetaSEXP, SEXP eta_muSEXP, SEXP tau_sq_muSEXP, SEXP lam0_0SEXP, SEXP lam1_0SEXP, SEXP sigma2_lam0SEXP, SEXP sigma2_lam1SEXP, SEXP edge_prob_thresholdSEXP, SEXP edge_prob_adjSEXP, SEXP epsilon_lamSEXP, SEXP num_step_lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type num_save(num_saveSEXP);
    Rcpp::traits::input_parameter< mat >::type theta_t(theta_tSEXP);
    Rcpp::traits::input_parameter< mat >::type ind_zero(ind_zeroSEXP);
    Rcpp::traits::input_parameter< mat >::type mu_treat(mu_treatSEXP);
    Rcpp::traits::input_parameter< mat >::type mu_ctrl(mu_ctrlSEXP);
    Rcpp::traits::input_parameter< cube >::type invcov_treat(invcov_treatSEXP);
    Rcpp::traits::input_parameter< cube >::type cov_treat(cov_treatSEXP);
    Rcpp::traits::input_parameter< cube >::type invcov_ctrl(invcov_ctrlSEXP);
    Rcpp::traits::input_parameter< cube >::type cov_ctrl(cov_ctrlSEXP);
    Rcpp::traits::input_parameter< cube >::type edge_treat(edge_treatSEXP);
    Rcpp::traits::input_parameter< cube >::type edge_ctrl(edge_ctrlSEXP);
    Rcpp::traits::input_parameter< vec >::type group_treat(group_treatSEXP);
    Rcpp::traits::input_parameter< vec >::type group_ctrl(group_ctrlSEXP);
    Rcpp::traits::input_parameter< vec >::type lambda0_t(lambda0_tSEXP);
    Rcpp::traits::input_parameter< vec >::type lambda1_t(lambda1_tSEXP);
    Rcpp::traits::input_parameter< vec >::type pi_treat(pi_treatSEXP);
    Rcpp::traits::input_parameter< vec >::type pi_ctrl(pi_ctrlSEXP);
    Rcpp::traits::input_parameter< vec >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< mat >::type cell_t(cell_tSEXP);
    Rcpp::traits::input_parameter< const int >::type G(GSEXP);
    Rcpp::traits::input_parameter< const int >::type N_int(N_intSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type ssp_v0(ssp_v0SEXP);
    Rcpp::traits::input_parameter< double >::type ssp_v1(ssp_v1SEXP);
    Rcpp::traits::input_parameter< double >::type ssp_l(ssp_lSEXP);
    Rcpp::traits::input_parameter< double >::type ssp_xi(ssp_xiSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_theta(epsilon_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type num_step_theta(num_step_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type eta_mu(eta_muSEXP);
    Rcpp::traits::input_parameter< double >::type tau_sq_mu(tau_sq_muSEXP);
    Rcpp::traits::input_parameter< double >::type lam0_0(lam0_0SEXP);
    Rcpp::traits::input_parameter< double >::type lam1_0(lam1_0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_lam0(sigma2_lam0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_lam1(sigma2_lam1SEXP);
    Rcpp::traits::input_parameter< double >::type edge_prob_threshold(edge_prob_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type edge_prob_adj(edge_prob_adjSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_lam(epsilon_lamSEXP);
    Rcpp::traits::input_parameter< int >::type num_step_lam(num_step_lamSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC_with_difficulty_based_matching(num_iter, num_save, theta_t, ind_zero, mu_treat, mu_ctrl, invcov_treat, cov_treat, invcov_ctrl, cov_ctrl, edge_treat, edge_ctrl, group_treat, group_ctrl, lambda0_t, lambda1_t, pi_treat, pi_ctrl, gam, cell_t, G, N_int, K, ssp_v0, ssp_v1, ssp_l, ssp_xi, epsilon_theta, num_step_theta, eta_mu, tau_sq_mu, lam0_0, lam1_0, sigma2_lam0, sigma2_lam1, edge_prob_threshold, edge_prob_adj, epsilon_lam, num_step_lam));
    return rcpp_result_gen;
END_RCPP
}
// update_mu_R
mat update_mu_R(mat theta_t, cube invcov_t, vec group_t, int G, int K, double eta_mu, double tau_sq_mu);
RcppExport SEXP _scNPM_update_mu_R(SEXP theta_tSEXP, SEXP invcov_tSEXP, SEXP group_tSEXP, SEXP GSEXP, SEXP KSEXP, SEXP eta_muSEXP, SEXP tau_sq_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type theta_t(theta_tSEXP);
    Rcpp::traits::input_parameter< cube >::type invcov_t(invcov_tSEXP);
    Rcpp::traits::input_parameter< vec >::type group_t(group_tSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type eta_mu(eta_muSEXP);
    Rcpp::traits::input_parameter< double >::type tau_sq_mu(tau_sq_muSEXP);
    rcpp_result_gen = Rcpp::wrap(update_mu_R(theta_t, invcov_t, group_t, G, K, eta_mu, tau_sq_mu));
    return rcpp_result_gen;
END_RCPP
}
// update_pi_R
vec update_pi_R(vec group_t, vec gam, int K);
RcppExport SEXP _scNPM_update_pi_R(SEXP group_tSEXP, SEXP gamSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type group_t(group_tSEXP);
    Rcpp::traits::input_parameter< vec >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(update_pi_R(group_t, gam, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scNPM_MCMC_with_difficulty_based_matching", (DL_FUNC) &_scNPM_MCMC_with_difficulty_based_matching, 39},
    {"_scNPM_update_mu_R", (DL_FUNC) &_scNPM_update_mu_R, 7},
    {"_scNPM_update_pi_R", (DL_FUNC) &_scNPM_update_pi_R, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_scNPM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
